### ISSUE TITLE
Incorrect Directory/File Paths in AgentBind.py

### ISSUE THREAD

**Issue by kalyanikottilil** [Pandaman-Ryan/AgentBind#1]
When saving a directory/file location name to a variable, extra forward slashes are saved into the path.
ex. line 98: dir_seqs = "%s/seqs_one_hot_%s/" %(dir_work_TF, suffix)

**Comment by Pandaman-Ryan** [comment]
Hi,

Thank you so much for your suggestion! We will clean it up in our next release.

In practice, the extra forward slashes should be ignored during the Python script execution. If that is not the case for you, would you mind letting us know your OS/environments/etc?

Cheers,
