### ISSUE TITLE
how to generate files in encode_model folder

### ISSUE THREAD

**Issue by kanglizhu** [Pandaman-Ryan/AgentBind#2]
Hello,
 I have downloaded the  "Data for experiments with the DeepSEA architecture", and  repeated your analyses using DeepSEA method.

Now I want to analyse my data using DeepSEA method, but I don't  know how to prepare the files in the encode_model folder? would you mind telling me how to prepare these files?

Best wishes 

kangli

**Comment by Pandaman-Ryan** [comment]
Hi Kangli,

Thank you for your question.

I would suggest you modify the file at {your-data-path}/table_matrix/table_core_motifs.txt. For each TF you are interested in, you will need: (1) TF ID (this can be any name you like to use as an identifier), (2) motif ID (from the folder at {your-data-path}/Jaspar-motifs/JASPAR2018_CORE_vertebrates_redundant_pfms_meme/), and ChIP-seq data for the TF of interest in the narrowpeak format.

The rest should be the same. You can simply execute:
python AgentBind.py 
--motif {your-data-path}/table_matrix/table_core_motifs.txt 
--workdir {your-work-path}
--datadir {your-data-path}
--resultdir {your-result-path}

Let me know if this does not work in your case.

**Comment by kanglizhu** [comment]
Hi,
Thank you for your reply. 

I'm curious about the files in the datadir. I know  how to prepare files in the genomes , Jaspar-motifs and TFBS_ENCODE folders, and table_core_motifs.txt in the table_matrix folder. I wonder are these files are enough for running AgentBind.py?

kangli

**Comment by Pandaman-Ryan** [comment]
Yes, they should be enough for your task.
