### ISSUE TITLE
predict TF binding sites of the whole genome

### ISSUE THREAD

**Issue by kanglizhu** [Pandaman-Ryan/AgentBind#3]
Hi，
I want to use one CTCF chip-seq data from LCL cell line to predict the whole potential CTCF binding sites across the chimpanzee genome. 

After running the command as you described, i got coordinates_pos.txt in the {my-work-path}/{TF-name}+LCL/seqs_one_hot_{b or c}/vis-weights-total/. I wonder whether this file contains all the potential CTCF binding sites in the genome, or this file can only reflect the actual binding sites for LCL cell line only? 

best wishes 

kangli

**Comment by Pandaman-Ryan** [comment]
Hi,

This file contains annotations for all the binding sites inside the ChIP-seq peaks you provided.

The genomic coordinates for these annotated sequences can be found in {my-work-path}/{TF-name}+LCL/seqs_one_hot_{b or c}/vis-weights-total/coordinates_pos.txt

and {my-work-path}/{TF-name}+LCL/seqs_one_hot_{b or c}/vis-weights-total/weight.txt gives you annotations for the forward and reverse strands for each sequence in the "coordinates_pos.txt" file, in the order of:

seq1 +
seq1 -
seq2 +
seq2 -
.....

Please let me know if you have any further questions.

Cheers,
-An

**Comment by kanglizhu** [comment]
Hi,

Since CTCF binding sites can be varied among different cell types. For example,  a subsequent analysis of  CTCF binding in three human cell lines showed that they had around 40-60% of the CTCF binding sites in common.

The coordinates_pos.txt can reflect the binding sites in the cell line I provided. I wonder whether it contains potential CTCF binding sites in other cell lines.

kangli

**Comment by Pandaman-Ryan** [comment]
For the CTCF binding sites in other cell lines, I am afraid you need to provide their ChIP-seq files and run experiments for them separately. The importance score annotations are specifically for the cell line that you use as input.
